name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to IPFS via Pinata
      uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
      with:
        pin-name: 'workshop2 deployment'
        path: './index.html' # Change to your directory path
        pinata-api-key: ${{ secrets.PINATA_API_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
        verbose: true
        remove-old: true

